// Créez une Promise qui se rejette après 1 seconde avec l'erreur "Une erreur est survenue". Gérez l'erreur avec `.catch()`.

// Pour lancer seulement ce test: npm run test -- 2.test.ts (attention il relance le test automatiquement à chaque modification de ce fichier)
export default function createFailingPromise() {
	// votre code ici
}
